name: build

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "16"

      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: DevAuth-artifacts
          path: |
            **/build/libs/*
            !**/build/libs/*-dev.jar
            !common/build/libs/*